name: "test-every-push"

on:
  push:
    branches:
      - main # 여기서는 main 브랜치에 push될 때마다 테스트를 실행하도록 설정하였습니다.

jobs:
  test:
    name: Test lint, tsc, build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # 이전 단계에서 캐시가 히트되지 않았을 때만 실행
        run: npm install

      - name: Run lint
        if: ${{ always() }} # 항상 실행하도록 설정
        run: npm run lint

      - name: Run tsc
        if: ${{ always() }}
        run: npm run tsc

      - name: Run build
        if: ${{ always() }}
        run: npm run build
